rest_controller:
    resource: ../src/Api/Controller
    type: annotation
    prefix: /

openapi_json:
    path:       /openapi.json
    controller: App\Api\Controller\ApiController::openApiJson
    methods:    [GET]
